services:
  main-db:
    image: couchdb:3
    restart: always
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
      - ./couchdb/local.ini:/opt/couchdb/etc/local.ini
    networks:
      - internal_network

  data-fetcher:
    image: data-fetcher
    environment:
      - ZENDO_ENV=dev
      - COUCHDB_USER=api
      - COUCHDB_PASSWORD=password
      - COUCHDB_DB=zendo
      - COUCHDB_URL=main-db:5984
    env_file:
      - ./data_fetcher/.env.docker
    ports:
      - "8080:8080"
    networks:
      - internal_network

  cron:
    image: zendo-cron
    environment:
      - FETCHER_HOST=data-fetcher
      - FETCHER_PORT=8080
    networks:
      - internal_network

  data-processor:
    image: data-processor
    environment:
      - ZENDO_ENV=dev
      - COUCHDB_DB=zendo
      - COUCHDB_USER=api
      - COUCHDB_PASSWORD=password
      - COUCHDB_URL=main-db:5984
    networks:
      - internal_network

  zendo-api:
    image: zendo-api
    environment:
      - ZENDO_ENV=dev
      - COUCHDB_USER=api
      - COUCHDB_PASSWORD=password
      - COUCHDB_DB=zendo
      - COUCHDB_URL=main-db:5984
    ports:
      - "8081:8081"
    networks:
      - internal_network

  zendo-web-app:
    image: zendo-web-app
    ports:
      - "3000:80"
    networks:
      - internal_network

volumes:
  couchdb_data:

networks:
  internal_network:
    name: internal_network
